### PR TITLE
Images Part 1: Add support for users to include images in their posts

### PR DESCRIPTION
**Pull request by gcheng21**
Update to allow for posts with images. Used regular expressions to capture user URLs of an image and convert it to an  element, so it can be displayed as an image on the webpage. Modified code in the servlet for processing the user text to convert it to an  element form, and modified the css to resize the image to fit in the post box.

### CODE REVIEW

**Comment by michelaburns** [comment]
Nice job!

**Comment by gcheng21** [comment]
@michelaburns could u approve the request

**Review by michelaburns — DISMISSED** [review]
Looks good!

**Comment by gcheng21** [comment]
> Looks good!

@michelaburns  I think there was a merge conflict, so it needs to be approved a second time :/ sorry about that; if you wouldnt mind approving again that would be perfect

**Review by michelaburns — APPROVED** [review]
Okay! Glad you sorted the merge conflicts

**Pull request merged**
