### PR TITLE
created MessageFeedServlet.java and feed.html

### PR DESCRIPTION
**Pull request by rababi**
I just created MessageFeedServlet.java and feed.html for the public feed portion of the project, it's super basic right now and I'm still in the process of trying to add more features, but since I haven't requested a pull yet I'd like to merge what I have so far. My Datastore.java also contains the getAllMessages method which I would like to merge into the master Datastore.java. 
Really sorry for getting to this now, it's been a super hectic week for me with 2 midterms but I'll definitely stay on top of things from now! Thanks a lot!

### CODE REVIEW

**Comment by elithrar** [comment]
Hey @rababi - there's a couple of conflicts you need to resolve here - since you're also making changes to `Datastore.java`.

What a conflict is & how to resolve it: https://help.github.com/en/articles/about-merge-conflicts

**Comment by rababi** [comment]
Just finished editing the Datastore.java, there was a bug in the getAllMessages method since it was calling the constructor with incorrect parameters, but now it's all fixed and compiling properly!

**Comment by michelaburns** [comment]
Yay! Happy you found the bug. Good job!

**Review by michelaburns — COMMENTED** [review]
Good job finding the bug!

**Comment by michelaburns** [comment]
Fixed the merge conflict on Datastore.java

**Review by michelaburns — APPROVED** [review]
Fixed

**Pull request merged**
